### ISSUE TITLE
Perhaps it should be a good idea to also change the position sort index?

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-indexer#101]
Perhaps it should be a good idea to also change the position sort index?
Currently it's Descending
https://github.com/block-core/blockcore-indexer/blob/master/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockIndexer.cs#L241

_Originally posted by @dangershony in https://github.com/block-core/blockcore-indexer/pull/97#r805410731_

**Comment by sondreb** [comment]
That would improve query performance? I'm having a peek at the database here and it returns the latest item first, so yes perhaps this should be changed.
