### ISSUE TITLE
Add computed table flow for DAO contract 

### ISSUE THREAD

**Issue by DavidGershony** [block-core/blockcore-indexer#120]
We should create it on demand, based on the address requested.
Need to add the erychment to the logs on the Cirrus node for DAO contracts.
Add caching of the currently calculated addresses to avoid multiple calls and executions of the same calculation.

**Comment by dangershony** [comment]
Let note here that any precalculation we make as enrichment will save a client call on the precomputed tables

**Comment by dangershony** [comment]
https://github.com/block-core/blockcore-indexer/commit/d7fd90d2c1f75907e5ba75caf88ad581e214888d
