### ISSUE TITLE
Build a decentralised solution for shared hosting of services such as indexer

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#130]
We must not be dependent on any cloud infrastructure that depends on corporate sponsorship. We can have that as an alternative, but IPs from DNS resolve should be semi-open for third party hosts.

**Comment by sondreb** [comment]
We could run the DNS node(s) that is part of our software suite, with some modifications. Instead of returning IPs for connected nodes, it will return IPs of known trusted hosts that are currently online.

So to start up the indexer, ("Blockcore Server"?) you configure a key pair on it, and on the DNS node(s) we'll add the pubkey of those hosts we trust and are allowed to update a single DNS entry (IP of server).

This is not to have decentralized domain names, but DNS servers that can be programmatically updated based upon signed messages provided by running instances of the indexer ("Blockcore Server").

**Comment by sondreb** [comment]
Dynamic DNS (DDNS) for DID is basically what we need to build. Multiple DNS servers that allows updates to be done by DIDs.

https://en.wikipedia.org/wiki/Dynamic_DNS

**Comment by dangershony** [comment]
> So to start up the indexer, ("Blockcore Server"?) 
This is for the indexer or for fullnodes? sounds like it should be a feature on the fullnode if anything.
Perhaps the registration to the dns could even have some type of service so it could be indexer/fullnode/vault etc...
not sure if it will be useful though for fullnodes asking for active ip addresses (but it could be useful for browser wallet instances to find indexers)

Also to consider filtering DNS by coin symbol

**Comment by dangershony** [comment]
Continuing on this I will now define tasks:

**agent** - is a daemon project that runs side by side of the indexer (or any other project that is open to querying by public nodes) and will update DNS servers with it's current ip and port and authenticate using a DID with schnorr signatures.
Bellow are the sub tasks such a daemon will perform:

- [ ] on interval check the public ip address of itself 
- [ ] sign messages designated to dns servers (payload = public ip address and port) using key specified in configuration 
- [ ] on interval send signed ip records to the dns servers specified in configuration 

**dns server** - is a daemon that runs on some public infrastructure (cloud) with static ip address, its job is to receive indexers requesting to register their own ip records, indexers that are active will be served to wallets that need block explorer services.

- [ ] configuration of public keys that are allowed to register ip records
- [ ] authenticate such requests and store ip and port 
- [ ] check indexers are live and accessible this should be done by the dns server not the agent to be sure the port is open 
- [ ] serve dns records to wallets that request ip addresses of active indexers for blockchain services 


This is a simple setup that comes to solve two problems 
- hosting: community members and potentially miners can run indexers and let wallet users query their indexers to get blockchain data, this will remove the need to deploy on costly always available cloud infrastructure while still keeping a reasonable service availability.
- less centralization: wallets will have options to query several domains to get ip addresses of running indexers and query for blockchain data form several sources, either to verify data and/or to be more resistant to censorship.

**Incentives**

The Blcockore community members will likely run such indexers however finding ways to have wallet users pay for usage will create more incentive to run indexers and bring more availability of the service, here are some ideas that come to mind
- coin burn: a user burns a small amount of coins and provides the burn as proof to get access to more services, this option is more targeted towards miners or big holders
- direct payment: to an indexer operator for guaranteed availability for certain services, such a protocol interaction could be built in to the wallet, this allows wallet users to change indexer operator in case of poor service.

Users will always have the option to run an self hosted indexer and not depend on any community indexers

**Comment by dangershony** [comment]
Closing this to read more go here
https://github.com/block-core/blockcore-dns
