### ISSUE TITLE
Return transaction index on transactions in block

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#138]
To improve sorting (make it deterministic), getting transactions should retrieve their index in the block they belong to.

**Comment by dangershony** [comment]
I will pick this up today

**Comment by dangershony** [comment]
Some work was done ins this commit https://github.com/block-core/blockcore-indexer/pull/110
However if I understand correctly you want the index also in the trx itself?
This api call `transaction/{transactionId}`

**Comment by dangershony** [comment]
done

![image](https://user-images.githubusercontent.com/7487930/164253979-a1f276c5-443a-4526-8d92-5372e95efa82.png)
