### ISSUE TITLE
Failure to display the balance of addresses

### ISSUE THREAD

**Issue by miladsoft** [block-core/blockcore-indexer#151]
When we want to increase the number of utxos with **/api/Wallet/splitcoins**, the balance of the addresses in the wallet changes, and this change is registered only for the address that was not previously zero. Other addresses that accept the new balance are not registered in the database

**Comment by dangershony** [comment]
We now know this happens because the split coins send the coins to legacy address not segwit.
This will be fixed when the wallet will be refactored to use segwit from derivation (as it should be)
