### ISSUE TITLE
Allow multiple tx hex to be retrieved in single API request

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#166]
The current implementation only supports a single hex value to be retrieved by appending /hex at the URL. For quick wallets that has many UTXOs, this results in many requests to indexers.

**Comment by DavidGershony** [comment]
What endpoint are you currently using?

**Comment by sondreb** [comment]
/hex is for sending in quick-mode, so my mistake on that.

This is the URL that is used to get single tx metadata, it's the same as explorer, random tx I found:

https://strax.indexer.blockcore.net/api/query/transaction/0ebb03c3be2e272667b6cb9b5d18d2ff6d9bdb2bdeca6beb00d330e62a56be40
