### ISSUE TITLE
Problem with Richlist

### ISSUE THREAD

**Issue by Igor-san** [block-core/blockcore-indexer#38]
Hi. The problem with the Rich List. Fresh installation of the Indexer. On Mongo 4 it did not work, I had to install version 5. It seems to work, but does not display a list of the rich.

I looked into the code and see that the call goes to the MapRichlist table, but there is no such table, but there is a RichList into which data is written in the BuildRichListComputingAndTableUpdatePipeline (https://github.com/block-core/blockcore-indexer/blob/83338e5d02a303ac297d57ffdd81e49402c3e1ca/src/Blockcore.Indexer/Sync/SyncTasks/RichListSync.cs#L180) code.

![MongiRichList](https://user-images.githubusercontent.com/30476065/144072154-e0a13a6c-8f87-4242-a603-eeec4040d709.png)

**Comment by dangershony** [comment]
It will be fixed in this PR
https://github.com/block-core/blockcore-indexer/pull/37

**Comment by dangershony** [comment]
this should be fixed now

![image](https://user-images.githubusercontent.com/7487930/144236359-c7c916a5-1249-4c05-971c-8d02756898e2.png)

**Comment by dangershony** [comment]
Thanks for checking @Igor-san
