### ISSUE TITLE
Add network weight to explorer

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-indexer#56]
network weight is how much stake is currently is currently finding blocks 
It can be added to this list.

![image](https://user-images.githubusercontent.com/7487930/149398496-448b09df-7bf6-4fba-9da5-82e0089eb791.png)

**Comment by dangershony** [comment]
Also as part of this task it would be nice to add on each address view what would be its potential network staking weight  
(or we could check if its staking and then add the weight)
this view
![image](https://user-images.githubusercontent.com/7487930/149415458-ec4f3495-dd82-4ff3-be27-e89be4e07400.png)

**Comment by sondreb** [comment]
Great suggestion =) Looking forward to this being added.

**Comment by dangershony** [comment]
It should be fairly easy we just need to also return the network weight in our periodic stats, then we can calculate the rest on demand

**Comment by sondreb** [comment]
We should obviously log it once a day and display as chart too.

**Comment by dangershony** [comment]
The network weight is calculated per block, so we could in theory add to each block what was the network weight when it was created.
also in order to compare netweight to the balance of an address i'd need to use some global param in the UI

**Comment by dangershony** [comment]
Fix in this commit

https://github.com/block-core/blockcore-indexer/pull/57/commits/2417b85aeba8455c4fcebfc248673b5b733204bb
