### ISSUE TITLE
Halt rollback of index database when chain database reset

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#6]
Currently the indexer is intelligent and is able to roll back when the chain database is reset. Sometimes this is needed or happens, but it should somehow be possible to halt the rollback while re-syncing. This is not a big problem on small chains, but for larger the computer will keep rolling back, and when the node catches up, indexing is slower than blockchain download.

**Comment by dangershony** [comment]
ah interesting yeah that is an issue, how would we halt it? if the fullnode wiped out the data store we should stop the indexer till its fully synced (or at least till fullnode headers are synced)

**Comment by dangershony** [comment]
This is now fixed
https://github.com/block-core/blockcore-indexer/blob/master/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockStartup.cs#L105
