### ISSUE TITLE
When a transaction is in the mempool, the balance is incorrect

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#7]
When a new transaction is in the mempool, the balance shown and returned by the indexer, is wrong. It corrects itself when the transaction is mined/staked.

**Comment by dangershony** [comment]
Is this now fixed?

**Comment by sondreb** [comment]
It is "fixed" by not returning it any longer? So that means incoming transactions to an address is not shown in the indexer until after it has been confirmed in a block?

This might not be a very optimal solution, especially not for BTC which has high block times.

**Comment by dangershony** [comment]
I think this is fixed now becuase now we track mempool spending not just receiving
