### ISSUE TITLE
Node APIs are listed on the Indexer after referencing Blockcore network packages

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#8]
- The OpenAPI documentation shows APIs from the Blockcore node software after the network definitions was referenced. They can't be executed, but should be hidden.

**Comment by sondreb** [comment]
The issue is clearly visible here: https://xds.indexer.blockcore.net/docs/index.html

"Node" is part of Blockcore, not part of the Indexer. Executing the methods doesn't work, but it shouldn't load at all.

![image](https://user-images.githubusercontent.com/309938/80550680-21facf00-89c1-11ea-9080-feeb70cd9281.png)

**Comment by sondreb** [comment]
The issue is related to ApplicationPart: https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.1

**Comment by dangershony** [comment]
This was fixed here 
https://github.com/block-core/blockcore-indexer/commit/fdbbc7c01072de1f1f26cefa6b1bc23636c39272
